"""add profile fields

Revision ID: 513787bb67bc
Revises: ffdc0a98111c
Create Date: 2025-02-26 20:58:18.757721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '513787bb67bc'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('profile_image_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('profile_image_url')
        batch_op.drop_column('bio')

    # ### end Alembic commands ###
